ERROR - 2022-06-22 10:04:22 --> Table 'contact_di4.client' doesn't exist
CRITICAL - 2022-06-22 10:04:22 --> Table 'contact_di4.client' doesn't exist
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT COUNT(`c...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(`c...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(`c...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(`c...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\app\Models\M_client.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Home.php(22): App\Models\M_client->tabel()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->grafik()
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-06-22 10:27:30 --> Invalid file: /contact/create.php
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/contact/create...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\View\View.php(487): CodeIgniter\View\View->render('/contact/create', NULL, true)
#2 C:\xampp\htdocs\contactapp_ci4\app\Views\contact\tabel.php(47): CodeIgniter\View\View->include('/contact/create')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('/contact/tabel', Array, true)
#6 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Akun.php(19): view('/contact/tabel')
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Akun->index()
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Akun))
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-22 12:51:38 --> Table 'contact_di4.client' doesn't exist
CRITICAL - 2022-06-22 12:51:38 --> Table 'contact_di4.client' doesn't exist
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT COUNT(`c...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(`c...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(`c...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(`c...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\app\Models\M_client.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Home.php(22): App\Models\M_client->tabel()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->grafik()
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-06-22 14:03:38 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:03:38 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->create()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:05:42 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:05:42 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->create()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:08:12 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:08:12 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(47): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->create()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:10:09 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:10:09 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->create()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:29:35 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:29:35 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(57): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->i()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:32:06 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:32:06 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(57): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->i()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:32:07 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 14:32:07 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(57): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->i()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 14:32:40 --> Table 'contact_di4.client' doesn't exist
CRITICAL - 2022-06-22 14:32:40 --> Table 'contact_di4.client' doesn't exist
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT COUNT(`c...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(`c...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(`c...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(`c...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\app\Models\M_client.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Home.php(22): App\Models\M_client->tabel()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->grafik()
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-06-22 16:32:23 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 16:32:23 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(57): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->i()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 16:32:25 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-06-22 16:32:25 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(57): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->i()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-22 16:34:15 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-06-22 16:34:15 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `co...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(57): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->i()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#11 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
